test(Metadata-Controller): add tests for metadata endpoints
catenax-ng/product-bpdm pull request #101
Opened 2022-06-24 12:28 UTC by nicoprow

2022-06-27 11:40 UTC, pazepaze requested changes

2022-06-27 11:40 UTC, pazepaze commented on src/test/kotlin/com/catenax/gpdm/controller/MetadataControllerIT.kt
> +        assertThat(returnedPage.content).containsAnyElementsOf(expected)
isSubsetOf seems more appropriate here

2022-06-27 11:40 UTC, pazepaze commented on src/test/kotlin/com/catenax/gpdm/controller/MetadataControllerIT.kt
> +     */
Test does not just check the second page though. Adjust documentation accordingly.

2022-06-28 12:07 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/controller/MetadataControllerIT.kt
> +     */
done

2022-06-28 12:07 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/controller/MetadataControllerIT.kt
> +        assertThat(returnedPage.content).containsAnyElementsOf(expected)
true, used that function instead

2022-06-28 12:07 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/controller/MetadataControllerIT.kt
> +     */
made the documentation more matching

2022-07-04 12:41 UTC, merged