fix(Opensearch): fix referencing index mappings resource
catenax-ng/product-bpdm pull request #131
Opened 2022-08-08 13:42 UTC by nicoprow

former way breaks in docker container

2022-08-08 13:57 UTC, pazepaze requested changes

2022-08-08 13:57 UTC, pazepaze commented on bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/impl/service/OpenSearchSyncStarterService.kt
> +        val indexMappings = String(indexResource.inputStream.readAllBytes(), Charset.defaultCharset())
Does not really have any consequences since default charset of our containers will be UTF-8, but we know our file has UTF-8 charset for sure since we versioned it like that, so call to defaultCharset() shouldn't be used to read it.
Just use constuctor without charset.

2022-08-09 06:49 UTC, nicoprow commented on bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/component/opensearch/impl/service/OpenSearchSyncStarterService.kt
> +        val indexMappings = String(indexResource.inputStream.readAllBytes(), Charset.defaultCharset())
Fixed

2022-08-09 06:50 UTC, pazepaze approved these changes

2022-08-09 07:23 UTC, merged