Implement legal entities output routes in gate
catenax-ng/product-bpdm pull request #133
Opened 2022-08-09 07:51 UTC by pazepaze

2022-08-09 14:58 UTC, nicoprow requested changes

2022-08-09 14:58 UTC, nicoprow commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/CdqConfig.kt
> +        return "/data-exchange/rest/v4/storages/${cdqProperties.storage}"
more elegant solution to this would be a val containing this string. Maybe even put such a val in the config properties body (not constructor) as its a derived config value

2022-08-09 14:58 UTC, nicoprow commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/CdqConfig.kt
> +        return "/data-clinic/rest/storages/${cdqProperties.storage}"
same as above

2022-08-10 07:30 UTC, pazepaze commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/CdqConfig.kt
> +        return "/data-exchange/rest/v4/storages/${cdqProperties.storage}"
Somehow it seems to work as val in constructor. This seems like the best solution since we can keep it as val then and don't need to resort to var.

2022-08-10 07:30 UTC, pazepaze commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/config/CdqConfig.kt
> +        return "/data-clinic/rest/storages/${cdqProperties.storage}"
done

2022-08-10 08:54 UTC, nicoprow approved these changes

2022-08-10 09:14 UTC, merged