fix(Properties): fix typo in dev keycloak resource
catenax-ng/product-bpdm pull request #144
Opened 2022-08-25 13:42 UTC by nicoprow

2022-08-25 13:49 UTC, pazepaze requested changes

2022-08-25 13:49 UTC, pazepaze commented on bpdm-gate/src/main/resources/application-auth.properties
> +keycloak.resource=Cl7-CX-BPDM
we should also remove the overwritten value for "keyclock-resource" in profile "int_auth" then, since the override is not needed anymore if the value in the base configuration is the same.

2022-08-25 13:49 UTC, pazepaze commented on bpdm-pool/src/main/resources/application-auth.properties
> +keycloak.resource=Cl7-CX-BPDM
same here

2022-08-26 07:07 UTC, nicoprow commented on bpdm-gate/src/main/resources/application-auth.properties
> +keycloak.resource=Cl7-CX-BPDM
Removed the unnecessary overwrite

2022-08-26 07:07 UTC, nicoprow commented on bpdm-pool/src/main/resources/application-auth.properties
> +keycloak.resource=Cl7-CX-BPDM
Removed the unnecessary overwrite

2022-08-26 07:08 UTC, pazepaze approved these changes

2022-08-26 07:16 UTC, merged