docs(README): update README for the newest changes
catenax-ng/product-bpdm pull request #203
Opened 2022-11-30 19:14 UTC by nicoprow

* Now separated into Pool and Gate
* Reflects the new app configuration without mentioning environments
* Added information about Github Workflows

2022-12-02 13:46 UTC, pazepaze requested changes

2022-12-02 13:46 UTC, pazepaze commented on README.adoc
> +This repository contains a Helm files for deploying the BPDM Gate to a Kubernetes environment.
a helm chart?

2022-12-02 13:46 UTC, pazepaze commented on README.adoc
> +An Ingress configuration for the GAte deployment could look like this:
Gate

2022-12-02 13:46 UTC, pazepaze commented on README.adoc
> +Consider that you would need to turn on `auth` and `pool-uath` profile first before overwriting any property in the corresponding properties file could take effect.
pool-auth

2022-12-05 14:29 UTC, nicoprow commented on README.adoc
> +Business partner records are divided into legal entities, sites and partner addresses, where a legal entity may have several sites and a site several partner addresses.
rephrased this part

2022-12-05 14:29 UTC, nicoprow commented on README.adoc
> +Furthermore, you can find here the configuration for the connection to the Spring datasource (currently, developed against PostgreSQL) and Opensearch.
fixed

2022-12-05 14:30 UTC, nicoprow commented on README.adoc
> +. view_company_data: For read-only endpoints of business partner data
changed the list formatting

2022-12-05 14:30 UTC, nicoprow commented on README.adoc
> +The file `application-cdq.properties` enables and configures the connection to a remote https://www.apimatic.io/apidocs/data-exchange/v/4_0#/rest/getting-started[CDQ API] form which the application c
fixed

2022-12-05 14:31 UTC, nicoprow commented on README.adoc
> +On default values this release deploys the latest image tagged as `main` from the repository's GitHub Container Registry.
True, I adapted the readme and will put in a fix on the default Helm charts in a separate pull request

2022-12-05 14:31 UTC, nicoprow commented on README.adoc
> +You can configure the these deployments in your value file as well.
fixed

2022-12-05 14:31 UTC, nicoprow commented on README.adoc
> +This repository contains a Helm files for deploying the BPDM Pool to a Kubernetes environment.
fixed

2022-12-05 14:31 UTC, nicoprow commented on README.adoc
> +This repository contains a Helm files for deploying the BPDM Gate to a Kubernetes environment.
fixed

2022-12-05 14:31 UTC, nicoprow commented on README.adoc
> +An Ingress configuration for the GAte deployment could look like this:
fixed

2022-12-05 14:31 UTC, nicoprow commented on README.adoc
> +Consider that you would need to turn on `auth` and `pool-uath` profile first before overwriting any property in the corresponding properties file could take effect.
fixed

2022-12-05 15:37 UTC, pazepaze approved these changes

2022-12-05 18:09 UTC, merged