feat(Gate-Validation): add endpoints to validate whether record can e…
catenax-ng/product-bpdm pull request #207
Opened 2022-12-02 01:04 UTC by nicoprow

Sharing members should have a way to determine whether a record can enter the sharing process

2022-12-02 14:21 UTC, pazepaze requested changes

2022-12-02 14:21 UTC, pazepaze commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteController.kt
> +            ApiResponse(responseCode = "400", description = "On malformed legal entity requests", content = [Content()]),
legal entity -> site

2022-12-02 14:21 UTC, pazepaze commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressController.kt
> +            ApiResponse(responseCode = "400", description = "On malformed legal entity requests", content = [Content()]),
legal entity -> address

2022-12-05 13:47 UTC, nicoprow commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteController.kt
> +            ApiResponse(responseCode = "400", description = "On malformed legal entity requests", content = [Content()]),
done

2022-12-05 13:47 UTC, nicoprow commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/AddressController.kt
> +            ApiResponse(responseCode = "400", description = "On malformed legal entity requests", content = [Content()]),
done

2022-12-05 14:21 UTC, pazepaze requested changes

2022-12-05 14:21 UTC, pazepaze commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/LegalEntityController.kt
> +            ApiResponse(responseCode = "400", description = "On malformed site requests", content = [Content()]),
Should be "legal entity" here and "site" in the SiteController

2022-12-05 14:21 UTC, pazepaze commented on bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/controller/SiteController.kt
> +            ApiResponse(responseCode = "400", description = "On malformed legal entity requests", content = [Content()]),
should be "site" here

2022-12-06 08:11 UTC, pazepaze approved these changes

2022-12-06 20:09 UTC, merged