chore(github-workflows): update to checkout action v3
catenax-ng/product-bpdm pull request #212
Opened 2022-12-06 08:22 UTC by pazepaze

use v3 everywhere, was still using v2 in some workflows

2022-12-06 20:12 UTC, nicoprow requested changes

2022-12-06 20:12 UTC, nicoprow commented on .github/workflows/helm-chart-release.yaml
> -  push:
best add trigger "when push to main" so we don't need to manually start the workflow every time we want to release a chart

2022-12-06 20:12 UTC, nicoprow commented on .github/workflows/helm-chart-release.yaml
> +      - name: Update helm dependencies for bpdm-pool
Is part of the DevSec template but I think not necessary. Please remove until we understand why it should be needed

2022-12-07 08:58 UTC, pazepaze commented on .github/workflows/helm-chart-release.yaml
> +      - name: Update helm dependencies for bpdm-pool
removed

2022-12-07 08:59 UTC, pazepaze commented on .github/workflows/helm-chart-release.yaml
> -  push:
added

2022-12-07 15:11 UTC, nicoprow approved these changes

2022-12-07 16:54 UTC, merged