feat(CDQ-Import): update existing business partner records on CDQ import
catenax-ng/product-bpdm pull request #62
Opened 2022-04-26 13:09 UTC by nicoprow

2022-04-27 12:00 UTC, pazepaze requested changes

2022-04-28 14:23 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/component/cdq/controller/CdqControllerImportIT.kt
> +        val updatedBusinessPartner1 =  CdqValues.businessPartner1.copy(lastModifiedAt = nowTime, names = listOf(modifiedName1))
I removed the the modification of the lastModifiedAt. A clean solution with a fixed time also needs a mocked fixed time clock in the service method. Our logic currently doesn't care about the lastModifiedAt field in the CDQ DTO anyway, so was quite redundant. However, I think we should try to change services (will open a ticket) so that they use Clock references with dependency injection for a better test support in the future.

2022-04-28 14:25 UTC, nicoprow commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.batch_versioned_data=true
Removed fetch depth property as we don't rely on eager fetching anymore

2022-04-29 07:20 UTC, pazepaze approved these changes

2022-04-29 07:30 UTC, merged