Feat/identifier search
catenax-ng/product-bpdm pull request #72
Opened 2022-05-06 11:48 UTC by pazepaze

2022-05-06 14:23 UTC, nicoprow requested changes
Looks good but should return an error when a non-existent identifier type key is specified to comply with the behaviour of the other endpoints

2022-05-09 07:56 UTC, pazepaze commented
> Looks good but should return an error when a non-existent identifier type key is specified to comply with the behaviour of the other endpoints

I understand that 404 should be returned on an endpoint that expects a single result or no result in that case. But isn't responding with an empty list in a case where there can be multiple results more appropriate? E.g. an empty list is also returned if the request contains only identifier **values** that are not found.

2022-05-09 09:30 UTC, pazepaze commented
> > Looks good but should return an error when a non-existent identifier type key is specified to comply with the behaviour of the other endpoints
> 
> I understand that 404 should be returned on an endpoint that expects a single result or no result, if there is no result.
> 
> But isn't responding with an empty list in a case where there can be multiple results more appropriate? Also, an empty list is currently returned if the request contains only identifier **values** that are not found.

We talked about it -> I'll change it.

2022-05-09 10:36 UTC, nicoprow approved these changes

2022-05-09 11:02 UTC, merged