cicd(Profiles): add multi-document application properties for profile…
catenax-ng/product-bpdm pull request #76
Opened 2022-05-10 11:45 UTC by nicoprow

… management

2022-05-12 09:45 UTC, nicoprow commented on README.adoc
> +7. Activate `persist` on environment `dev` and `elastic` on environment `int`: `mvn clean spring-boot:run -Dspring.profiles.active=persist,elastic,dev_persist,int_elastic`
change implemented

2022-05-12 13:51 UTC, pazepaze requested changes

2022-05-12 13:51 UTC, pazepaze commented on src/main/resources/application.properties
> -bpdm.bpn.search-request-limit=5000
Was this property deleted accidentally? I know it's not really needed in the properties file since we already set a default via in the @ConfigurationProperties annotated class, but we have set the default for other properties in both places.

2022-05-13 07:25 UTC, nicoprow commented on src/main/resources/application.properties
> -bpdm.bpn.search-request-limit=5000
oops, yea my bad. Must have been accidentally deleted during merging

2022-05-13 07:32 UTC, pazepaze approved these changes

2022-05-13 07:50 UTC, merged