feat(Elasticsearch): recreate Elasticsearch index when Entity changes
catenax-ng/product-bpdm pull request #90
Opened 2022-05-24 11:46 UTC by nicoprow

2022-05-25 12:03 UTC, pazepaze commented on src/main/kotlin/com/catenax/gpdm/component/elastic/impl/service/ElasticSyncStarterService.kt
> +    @Throws(BpdmElasticIndexException::class)
Is this explicit @Throws needed because of transaction handling/rollback or is this some spring/java interoperability thing?

2022-05-25 12:24 UTC, pazepaze commented on src/test/kotlin/com/catenax/gpdm/util/ElasticsearchValidIndexInitializer.kt
> +class ElasticsearchValidIndexInitializer : ApplicationContextInitializer<ConfigurableApplicationContext> {
kdoc for this class would be nice (probably some sentence on class level )

2022-05-25 12:26 UTC, pazepaze commented on src/test/kotlin/com/catenax/gpdm/component/elastic/ElasticSearchStartupIT.kt
> +    @Test
The fact that I don't understand why there is a search result here and not in the other test makes me think that some documentation, maybe given/when/then would be nice here

2022-05-30 12:45 UTC, nicoprow commented on src/main/kotlin/com/catenax/gpdm/component/elastic/impl/service/ElasticSyncStarterService.kt
> +    @Throws(BpdmElasticIndexException::class)
Not needed, just for docu purposes. Put it into Kdoc

2022-05-30 12:45 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/component/elastic/ElasticSearchStartupIT.kt
> +
Done

2022-05-30 12:45 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/util/ElasticsearchOutdatedIndexInitializer.kt
> +class ElasticsearchOutdatedIndexInitializer : ApplicationContextInitializer<ConfigurableApplicationContext> {
Done

2022-05-30 12:45 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/util/ElasticsearchValidIndexInitializer.kt
> +class ElasticsearchValidIndexInitializer : ApplicationContextInitializer<ConfigurableApplicationContext> {
Done

2022-05-30 12:45 UTC, nicoprow commented on src/test/kotlin/com/catenax/gpdm/component/elastic/ElasticSearchStartupIT.kt
> +    @Test
Done

2022-05-30 12:46 UTC, nicoprow commented on src/main/kotlin/com/catenax/gpdm/component/elastic/impl/service/ElasticSyncStarterService.kt
> +    fun clearElastic(): Boolean {
Leftover code, removed it

2022-05-30 14:10 UTC, pazepaze requested changes

2022-05-30 14:10 UTC, pazepaze commented on src/test/resources/elastic/index.json
> +}
This needs to be adjusted after each "schema change"...

Maybe test the "valid case" this way instead:
- Create two tests with @Ordered and @DirtiesContext so the spring context is recreated and check if data exported to elastic is still there from the first of those tests

2022-06-02 08:39 UTC, pazepaze approved these changes

2022-06-02 09:01 UTC, merged