Feat/split partner response
catenax-ng/product-bpdm pull request #96
Opened 2022-06-10 07:33 UTC by pazepaze

2022-06-21 10:58 UTC, nicoprow requested changes
As we have discussed: Duplicate code in the DTOs should be removed. 

Other than that, works well and I notice performance improvement on big datasets.

2022-06-21 10:58 UTC, nicoprow commented on src/main/kotlin/com/catenax/gpdm/service/SiteService.kt
> +        siteRepository.joinAddresses(sites)
also needs to join the dependencies of the addresses here to prevent lazy fetching

2022-06-24 08:56 UTC, pazepaze commented on src/main/kotlin/com/catenax/gpdm/service/SiteService.kt
> +        siteRepository.joinAddresses(sites)
done

2022-06-27 07:16 UTC, nicoprow approved these changes

2022-06-28 09:09 UTC, merged