feat(Logging): Add logs with user and request information
catenax-ng/product-bpdm pull request #97
Opened 2022-06-10 10:06 UTC by nicoprow

Added ERROR, WARN, INFO und DEBUG level logs

INFO - Covers configuration information, request start/finish and most important events regarding Export/Import, creation and updating of business partners including BPNs
DEBUG - Some more details during important events

More in-depth error logging when we tackle exception handling

Logging user name and request id comes in handy when using tools like Kibana later but can be very verbose on local. So that's why you can disable adding the username and request id to each log in the application.properties.

2022-06-14 20:36 UTC, the-tatanka commented
https://www.veracode.com/security/java/cwe-117

The input must be logged before it is logged.

2022-06-21 09:19 UTC, pazepaze requested changes

2022-06-21 09:19 UTC, pazepaze commented on src/main/kotlin/com/catenax/gpdm/component/cdq/service/PartnerImportService.kt
>                  throw exception
log and re-throwing same exception is kind of an antipattern I think

2022-06-21 09:19 UTC, pazepaze commented on src/main/kotlin/com/catenax/gpdm/component/elastic/impl/service/ElasticSyncService.kt
>                  throw exception
log and re-throwing same exception is kind of an antipattern I think

2022-06-21 14:08 UTC, nicoprow commented on src/main/resources/application.properties
> +spring.profiles.include=persist,auth,cdq,elastic,logging
Leftover from an abandoned approach- Has been removed

2022-06-21 14:12 UTC, nicoprow commented on src/main/resources/logback-spring.xml
> +                %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%.30X{user}){blue} %clr(%X{request}){magenta} %clr([%-15.15t]){faint}
Yea, I was aware of the problem and not sure how to tackle it. I went a third way since we distinguish between full and min console output configuration. I just gave user and request a fixed length as well which makes it more verbose but aligns the log messages

2022-06-21 14:15 UTC, nicoprow commented on src/main/kotlin/com/catenax/gpdm/config/LoggingConfig.kt
> +}
Yes, when invoking Async annotated methods, SpringBoot uses these decorators to modify the context of the new thread. You can check it when executing an async import. The thread changes but the request-ID stays the same. Only possible with this class.

2022-06-21 14:18 UTC, nicoprow commented on src/main/kotlin/com/catenax/gpdm/component/cdq/service/PartnerImportService.kt
>                  throw exception
I did it here because this method is currently used in another thread, so the exception is actually not shown unless it is logged here. I throw the exception in order to stop the whole async execution.

But to make it more clean and less anti-pattern I now exchanged the throw with a return, so the exception is resolved after it's logged and written into the sync-record

2022-06-21 14:18 UTC, nicoprow commented on src/main/kotlin/com/catenax/gpdm/component/elastic/impl/service/ElasticSyncService.kt
>                  throw exception
see above

2022-06-21 14:19 UTC, nicoprow commented on src/main/resources/logback-spring.xml
> +                %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
True, was auto-formatting. Fixed it

2022-06-22 14:42 UTC, pazepaze approved these changes

2022-06-24 06:40 UTC, merged